"use strict"
console.log( '5' + '2')
console.log('5' + 2)
console.log(5 + '2')
console.log(5 + 2)
console.log('5' * '2')
console.log('5' - '2')
console.log('5' / '2')
console.log('5' % '2')
console.log('5s' * '2')
console.log('5s' + '2')
console.log((-'5') + (-'2'))
console.log('5' * 1 + '2' * 1)
console.log('5' * '1' + '2' * '1')
console.log('' + 3 + 1)
